import React, { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheck, faCircleNodes, faListUl, faPlus } from '@fortawesome/free-solid-svg-icons';
import './style.scss';
import Topbar from '../../../components/Topbar';
import NoteModel from '../../../model/NoteModel';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button, Checkbox, Input } from 'basicui';
import MainSection from '../../../components/MainSection';
import { saveNote } from '../NotePage/service';
import { getRecentlyCreatedNote } from './service';
import RecentNote from './RecentNote';
import { appendNoteItem } from '../../../store/actions/NoteActions';

interface Props {
  location: any;
  space: string;
}

const NewNotePage = (props: Props) => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const authorization = useSelector((state: any) => state.authorization);
  const [copy, setCopy] = useState(false);
  const [recentNote, setRecentNote] = useState<NoteModel>({
    name: '',
    labels: [],
    reference: ''
  });

  const [state, setState] = useState<NoteModel>({
    _id: undefined,
    content: '',
    labels: [],
    name: '',
    reference: ''
  });

  useEffect(() => {
    if (authorization.isAuth) {
      getRecentlyCreatedNote(props.space, authorization).then((response: NoteModel) => {
        setRecentNote(response);
      });
    }
  }, [authorization]);

  useEffect(() => {
    console.log("****", recentNote);
  }, [recentNote]);

  const handleChange = (event: any) => {
    setState({ ...state, [event.currentTarget.name]: event.currentTarget.value });
  };

  const handleRecentNoteChange = (_note: NoteModel) => {
    setRecentNote({ ...recentNote, ..._note });
  };

  const save = () => {
    let _note = { ...state };
    if (copy) {
      const { name, reference, _id, autoGeneratedSummary, summary, contentText, content, createdAt, type, ...rest } = recentNote;
      _note = { ...state, ...rest };
    }
    saveNote(props.space, _note, authorization).then((response) => {
      dispatch(appendNoteItem(response.note));
      navigate(`/${props.space}/note/${response.note.reference}`);
    })
  }

  const onCopyToggle = (event: any) => {
    setCopy(event.currentTarget.checked);
  }

  return (
    <div className="page-animate">
      <Topbar title="Create new note" space={props.space} />
      <MainSection>
        <form id="new-page" onSubmit={save} className='new-note-form'>
          <Input name="name" value={state.name} onInput={handleChange} label='Note name' />
          {recentNote && <>
            <Checkbox
              name="check"
              onInput={onCopyToggle} label='Copy metadata from recently created note' />

            <RecentNote editable={copy} note={recentNote} onChange={handleRecentNoteChange} />
          </>}
        </form>
        <div className="footer">
          <div />
          <div className="footer-right">
            <Button onClick={save}>
              <FontAwesomeIcon icon={faPlus} /> Create
            </Button>
          </div>
        </div>
      </MainSection>
    </div>
  );
};

export default NewNotePage;
